application: php-school
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.php
  
- url: /opdracht1\.php
  script: opdracht1.php
  
- url: /opdracht2\.php
  script: opdracht2.php
  
- url: /opdracht3\.php
  script: opdracht3.php
  
- url: /opdracht4\.php
  script: opdracht4.php
  
- url: /opdracht5\.php
  script: opdracht5.php
  
- url: /opdracht6\.php
  script: opdracht6.php
  
- url: /opdracht7\.php
  script: opdracht7.php
  
- url: /opdracht8\.php
  script: opdracht8.php
  
- url: /opdracht9\.php
  script: opdracht9.php
  
- url: /opdracht11\.php
  script: opdracht11.php
  
- url: /mrwheely\.php
  script: mrwheely.php
  
- url: /opdracht13\.php
  script: opdracht13.php
  
- url: /opdracht14\.php
  script: opdracht14.php
  
- url: /opdracht15\.php
  script: opdracht15.php
  
- url: /nederlands\.php
  script: nederlands.php
  
  
  